//ExpansionShared/ExpansionShared.far/work.iff

//Example
/*worklistExample: {
  work: {
    Expansion: string,
    level_0: {
      Car: {
        img(URL),
        Name(string),
      }
      salary: number,
      begintime: number,
      endtime: number,
      chanceCardEs: string,
      chanceCardEffectEs: string,
      descriptionEs: string,
      promotionEs: string,
      promotionUs: string,
      moodChangesPerHour: [
        Hunger,
        Comfort,
        Higiene,
        Bladder,
        Emergy,
        Fun,
        Social,
      ],
      friends: number,
      skills: [Cooking, Mechanical, Charisma, Body, Logic, Creativity],
    }
    level_1: {
      Car: {
        img(URL),
        Name(string),
      }
      salary: number,
      begintime: number,
      endtime: number,
      chanceCardEs: string,
      chanceCardEffectEs: string,
      descriptionEs: string,
      promotionEs: string,
      promotionUs: string,
      moodChangesPerHour: [
        Hunger,
        Comfort,
        Higiene,
        Bladder,
        Emergy,
        Fun,
        Social,
      ],
      friends: number,
      skills: [Cooking, Mechanical, Charisma, Body, Logic, Creativity],
    }
    level_2: {
      Car: {
        img(URL),
        Name(string),
      }
      salary: number,
      begintime: number,
      endtime: number,
      chanceCardEs: string,
      chanceCardEffectEs: string,
      descriptionEs: string,
      promotionEs: string,
      promotionUs: string,
      moodChangesPerHour: [
        Hunger,
        Comfort,
        Higiene,
        Bladder,
        Emergy,
        Fun,
        Social,
      ],
      friends: number,
      skills: [Cooking, Mechanical, Charisma, Body, Logic, Creativity],
    }
    level_3: {
      Car: {
        img(URL),
        Name(string),
      }
      salary: number,
      begintime: number,
      endtime: number,
      chanceCardEs: string,
      chanceCardEffectEs: string,
      descriptionEs: string,
      promotionEs: string,
      promotionUs: string,
      moodChangesPerHour: [
        Hunger,
        Comfort,
        Higiene,
        Bladder,
        Emergy,
        Fun,
        Social,
      ],
      friends: number,
      skills: [Cooking, Mechanical, Charisma, Body, Logic, Creativity],
    }
    level_4: {
      Car: {
        img(URL),
        Name(string),
      }
      salary: number,
      begintime: number,
      endtime: number,
      chanceCardEs: string,
      chanceCardEffectEs: string,
      descriptionEs: string,
      promotionEs: string,
      promotionUs: string,
      moodChangesPerHour: [
        Hunger,
        Comfort,
        Higiene,
        Bladder,
        Emergy,
        Fun,
        Social,
      ],
      friends: number,
      skills: [Cooking, Mechanical, Charisma, Body, Logic, Creativity],
    }
    level_5: {
      Car: {
        img(URL),
        Name(string),
      }
      salary: number,
      begintime: number,
      endtime: number,
      chanceCardEs: string,
      chanceCardEffectEs: string,
      descriptionEs: string,
      promotionEs: string,
      promotionUs: string,
      moodChangesPerHour: [
        Hunger,
        Comfort,
        Higiene,
        Bladder,
        Emergy,
        Fun,
        Social,
      ],
      friends: number,
      skills: [Cooking, Mechanical, Charisma, Body, Logic, Creativity],
    }
    level_6: {
      Car: {
        img(URL),
        Name(string),
      }
      salary: number,
      begintime: number,
      endtime: number,
      chanceCardEs: string,
      chanceCardEffectEs: string,
      descriptionEs: string,
      promotionEs: string,
      promotionUs: string,
      moodChangesPerHour: [
        Hunger,
        Comfort,
        Higiene,
        Bladder,
        Emergy,
        Fun,
        Social,
      ],
      friends: number,
      skills: [Cooking, Mechanical, Charisma, Body, Logic, Creativity],
    }
    level_7: {
      Car: {
        img(URL),
        Name(string),
      }
      salary: number,
      begintime: number,
      endtime: number,
      chanceCardEs: string,
      chanceCardEffectEs: string,
      descriptionEs: string,
      promotionEs: string,
      promotionUs: string,
      moodChangesPerHour: [
        Hunger,
        Comfort,
        Higiene,
        Bladder,
        Emergy,
        Fun,
        Social,
      ],
      friends: number,
      skills: [Cooking, Mechanical, Charisma, Body, Logic, Creativity],
    }
    level_8: {
      Car: {
        img(URL),
        Name(string),
      }
      salary: number,
      begintime: number,
      endtime: number,
      chanceCardEs: string,
      chanceCardEffectEs: string,
      descriptionEs: string,
      promotionEs: string,
      promotionUs: string,
      moodChangesPerHour: [
        Hunger,
        Comfort,
        Higiene,
        Bladder,
        Emergy,
        Fun,
        Social,
      ],
      friends: number,
      skills: [Cooking, Mechanical, Charisma, Body, Logic, Creativity],
    }
    level_9: {
      Car: {
        img(URL),
        Name(string),
      }
      salary: number,
      begintime: number,
      endtime: number,
      chanceCardEs: string,
      chanceCardEffectEs: string,
      descriptionEs: string,
      promotionEs: string,
      promotionUs: string,
      moodChangesPerHour: [
        Hunger,
        Comfort,
        Higiene,
        Bladder,
        Emergy,
        Fun,
        Social,
      ],
      friends: number,
      skills: [Cooking, Mechanical, Charisma, Body, Logic, Creativity],
    }
  }
}
  */

const worklist = [
  {
    expansion: "Juego Base",
    carrerNameEs: "Negocios",
    carrerNameUs: "Business",
    levels: [
      {
        level:1,
        nameEs: "Encargado del correo",
        nameUs: "Mailroom Clerk",
        car: {
          image: "",
          name: "",
        },
        salary: 120,
        begintime: 9,
        endtime: 15,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "Salario mínimo, pero entrarás en una de las megacorporaciones de SimCity. Te tienes que encargar de que la fotocopiadora y la máquina de café funcionen a la perfección. Debes ser organizado, estar disponible, y mostrarte sociable y cordial cuando vayas empujando tu carrito por los pasillos. Puede que algún ejecutivo de la compañía tenga buen ojo y te tenga en cuenta cuando haya una vacante en un puesto superior.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [0, 0, 0, 0, -5, 0, 0],
        friends: 0,
        skills: [0, 0, 0, 0, 0, 0],
      },
      {
        level:2,
        nameEs: "Ayudante ejecutivo",
        nameUs: "Executive Assistant",
        Car: {
          image: "",
          name: "",
        },
        salary: 180,
        begintime: 9,
        endtime: 16,
        chanceCardEs: "El jefe ha llegado tarde para hacer un envío importantísimo esta noche. Te has ofrecido a llevar el paquete al aeropuerto. Por tu iniciativa, el jefe te recompensa con una bonificación de 1000 dólares.",
        chanceCardEffectEs: "§1000",
        descriptionEs: "Se trabajan muchas horas, pero tendrás ocasión de ponerte al teléfono, mejorar tu habilidad de trato con la gente, y más ocasiones de complacer al Jefe. Si mejoras tus habilidades mecánicas quizá puedas arreglar la fotocopiadora la próxima vez que ese trasto se averíe. Eso sí que hará que el jefe se fije en ti.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [0, 0, 0, 0, -4, 0, 0],
        friends: 0,
        skills: [0, 0, 0, 0, 0, 0],
      },
      {
        level:3,
        nameEs: "Representante de ventas",
        nameUs: "Field Sales Rep",
        car: {
          image: "",
          name: "",
        },
        salary: 250,
        begintime: 9,
        endtime: 16,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "Antes de progresar en la compañía tendrás que ganártelo con muchas horas de carretera. Cumple con tu cupo de ventas (el carisma es imprescindible) y establece contactos, y estarás más cerca de un ascenso que te lleve a un despacho sin ruedas.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [0, 0, 0, 0, -5, 0, 0],
        friends: 0,
        skills: [0, 200, 0, 0, 0, 0],
      },
      {
        level:4,
        nameEs: "Ejecutivo adjunto",
        nameUs: "Junior Executive",
        car: {
          image: "",
          name: "",
        },
        salary: 320,
        begintime: 9,
        endtime: 16,
        chanceCardEs: "¡Qué vergüenza! Una copa de ponche de más en la fiesta de la oficina, y has hecho el ridículo más espantoso. Pierdes un punto de carisma.",
        chanceCardEffectEs: "-1 punto de carisma",
        descriptionEs: "Ahora tienes esclavos propios a los que tratar a patadas, un cubículo para ti solo, y un sueldo decente... pero aún te queda un largo camino hasta acceder a los cuartos de baño decentes. Mantener buenas relaciones con la gente, y probar tu talento para la lógica, hará que tus superiores se fijen en ti.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-1, 0, -1, 0, -6, -1, 0],
        friends: 1,
        skills: [0, 200, 200, 0, 0, 0],
      },
      {
        level:5,
        nameEs: "Ejecutivo",
        nameUs: "Executive",
        car: {
          image: "",
          name: "",
        },
        salary: 400,
        begintime: 9,
        endtime: 16,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "Dispones de un ejecutivo adjunto a tus órdenes, y un despacho de los de verdad, con puerta que se cierra y todo. Lo malo es que, en la compañía para la que trabajas, el nivel de ejecutivos está superpoblado. Una mejora en tus habilidades y una buena actitud en el trabajo te ayudarán a destacar entre los demás e impresionar a tus superiores.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-1, 0, -2, 0, -6, -1, 0],
        friends: 3,
        skills: [0, 200, 200, 0, 200, 0],
      },
      {
        level:6,
        nameEs: "Administrador senior",
        nameUs: "Senior Manager",
        car: {
          image: "",
          name: "",
        },
        salary: 520,
        begintime: 9,
        endtime: 16,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "Tu sueldo se dispara, porque ahora tienes a tu cargo el control de varias franquicias. Hay muchos ejecutivos a tus órdenes, de manera que las habilidades de carisma y lógica te ayudarán a resolver discusiones y a hacer que los diferentes equipos funcionen sin problemas. Tendrás que mejorar tu drive, de ahora en adelante cerrarás muchos tratos en el campo de golf. Así que tampoco estará de más cuidar tu aspecto físico.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-2, 0, -2, 0, -7, -1, 0],
        friends: 6,
        skills: [0, 200, 300, 0, 300, 200],
      },
      {
        level:7,
        nameEs: "Consejero",
        nameUs: "Vice President",
        car: {
          image: "",
          name: "",
        },
        salary: 660,
        begintime: 9,
        endtime: 17,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "Tienes un despacho con vistas a dos calles. Otro aumento de sueldo. Pero la competencia en este piso es muy dura. Sigue cultivando tus habilidades y haz muchos amigos, nunca sabes cuándo los vas a necesitar.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-2, 0, -3, 0, -6, -2, 0],
        friends: 8,
        skills: [0, 200, 400, 200, 400, 200],
      },
      {
        level:8,
        nameEs: "Vicepresidente",
        nameUs: "President",
        car: {
          image: "",
          name: "",
        },
        salary: 800,
        begintime: 9,
        endtime: 17,
        chanceCardEs: "Con sabiduría y valor, juzgas el caso del gangster más notorio de SimCity y te ganas la admiración de toda la Nación Sim. Te ofrecen un contrato por hacer un libro, con un anticipo de 5000 dólares.",
        chanceCardEffectEs: "§5000",
        descriptionEs: "La compañía manda cada mañana a tu casa un cochazo para recogerte. Tu despacho es una suite en el piso superior, y tu nómina da vértigo. Tu creatividad está al máximo, te sientes el más sagaz, el más poderoso. Pero todo tiene su lado malo: más estrés, y a algunos de tus vecinos no les gustará que tengas tanto éxito (nada que no se arregle con invitarlos a una barbacoa en el jardín de tu casa. Y quién sabe, así quizá conozcas a más gente...)",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-2, 0, -3, 0, -7, -2, 0],
        friends: 10,
        skills: [0, 200, 500, 200, 600, 300],
      },
      {
        level:9,
        nameEs: "Presidente",
        nameUs: "CEO",
        car: {
          image: "",
          name: "",
        },
        salary: 950,
        begintime: 9,
        endtime: 16,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "El mandamás de tu compañía. Pero, ¿puede un ejecutivo poderoso y eficaz equilibrar sus responsabilidades en el trabajo con las necesidades de su cónyuge, sus hijos y amigos? Tus responsabilidades sociales crecen, quizá sea hora de que te traslades a una casa más grande para recibir a los figurones como se merecen.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-3, 0, -5, 0, -8, -3, 0],
        friends: 12,
        skills: [0, 200, 600, 200, 700, 500],
      },
      {
        level:10,
        nameEs: "Magnate",
        nameUs: "Business Tycoon",
        car: {
          image: "",
          name: "",
        },
        salary: 1200,
        begintime: 9,
        endtime: 15,
        chanceCardEs: "Estás completamente quemado en tu profesión. En un arranque de inspiración, dejas el mundo de los negocios e inicias una nueva carrera en el deporte. Por fin te van a servir de algo todas las horas que has pasado en el campo de golf. El equipo local te ofrece un puesto como titular, y aceptas.",
        chanceCardEffectEs: "Cambio de carrera a Deportes de alto riesgo | nivel 4 - Titular",
        descriptionEs: "Eres un empresario agresivo, diriges un conglomerado con oficinas en todo el mundo. Pero, ahora que eres un pilar de la sociedad, ni te lo imaginas... Se espera que hagas donativos para caridad, para mantener tu posición entre tus conciudadanos sims. Pese a los inconvenientes, con éxito la vida es bella.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-5, 0, -6, 0, -11, -4, 0],
        friends: 14,
        skills: [0, 200, 800, 200, 900, 600],
      },
    ],
  },
  {
    expansion: "Juego Base",
    carrerNameEs: "Entretenimiento",
    carrerNameUs: "Entertainment",
    levels: [
      {
        level:1,
        nameEs: "Camarero",
        nameUs: "Waiter",
        car: {
          image: "",
          name: "",
        },
        salary: 100,
        begintime: 9,
        endtime: 15,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [0, 0, 0, 0, -5, 0, 0],
        friends: 0,
        skills: [0, 0, 0, 0, 0, 0],
      },
      {
        level:2,
        nameEs: "Extra",
        nameUs: "Extra",
        car: {
          image: "",
          name: "",
        },
        salary: 150,
        begintime: 9,
        endtime: 15,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [0, 0, 0, 0, -5, 0, 0],
        friends: 0,
        skills: [0, 0, 0, 0, 0, 0],
      },
      {
        level:3,
        nameEs: "Figurante",
        nameUs: "Bit Player",
        car: {
          image: "",
          name: "",
        },
        salary: 200,
        begintime: 9,
        endtime: 15,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [0, 0, 0, 0, -6, 0, 0],
        friends: 0,
        skills: [0, 0, 200, 0, 0, 0],
      },
      {
        level:4,
        nameEs: "Especialista de cine",
        nameUs: "B-Movie Star",
        car: {
          image: "",
          name: "",
        },
        salary: 275,
        begintime: 9,
        endtime: 16,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-1, 0, -1, 0, -6, -1, 0],
        friends: 2,
        skills: [0, 0, 200, 200, 0, 0],
      },
      {
        level:5,
        nameEs: "Estrella de series B",
        nameUs: "B-Movie Star",
        car: {
          image: "",
          name: "",
        },
        salary: 375,
        begintime: 10,
        endtime: 17,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-1, 0, -2, 0, -6, -1, 0],
        friends: 4,
        skills: [0, 0, 300, 300, 0, 100],
      },
      {
        level:6,
        nameEs: "Secundario",
        nameUs: "Supporting Player",
        car: {
          image: "",
          name: "",
        },
        salary: 500,
        begintime: 10,
        endtime: 18,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-1, 0, -2, 0, -6, -1, 0],
        friends: 6,
        skills: [0, 100, 400, 400, 0, 200],
      },
      {
        level:7,
        nameEs: "Estrella de la TV",
        nameUs: "TV Star ",
        car: {
          image: "",
          name: "",
        },
        salary: 650,
        begintime: 10,
        endtime: 18,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-2, 0, -3, 0, -6, -2, 0],
        friends: 8,
        skills: [0, 100, 600, 500, 0, 300],
      },
      {
        level:8,
        nameEs: "Estrella de Cine",
        nameUs: "Feature Star",
        car: {
          image: "",
          name: "",
        },
        salary: 900,
        begintime: 17,
        endtime: 1,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-2, 0, -3, 0, -7, -2, 0],
        friends: 10,
        skills: [0, 200, 700, 600, 0, 400],
      },
      {
        level:9,
        nameEs: "Estrella de Teatro",
        nameUs: "Broadway Star",
        car: {
          image: "",
          name: "",
        },
        salary: 1100,
        begintime: 10,
        endtime: 17,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-3, 0, -5, 0, -8, -3, 0],
        friends: 12,
        skills: [0, 200, 800, 700, 0, 700],
      },
      {
        level:10,
        nameEs: "Superestrella",
        nameUs: "Superstar",
        car: {
          image: "",
          name: "",
        },
        salary: 1400,
        begintime: 10,
        endtime: 15,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-6, 0, -8, 0, -13, -5, 0],
        friends: 14,
        skills: [0, 200, 1000, 800, 0, 1000],
      },
    ],
  },
  {
    expansion: "Juego Base",
    carrerNameEs: "Cuerpos de seguridad",
    carrerNameUs: "Law Enforcement",
    levels: [
      {
        level:1,
        nameEs: "Guardia de seguridad",
        nameUs: "Security Guard",
        car: {
          image: "",
          name: "",
        },
        salary: 240,
        begintime: 0,
        endtime: 6,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [0, 0, 0, 0, -5, 0, 0],
        friends: 0,
        skills: [0, 0, 0, 0, 0, 0],
      },
      {
        level:2,
        nameEs: "Cadete",
        nameUs: "Cadet",
        car: {
          image: "",
          name: "",
        },
        salary: 320,
        begintime: 9,
        endtime: 15,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [0, 0, 0, 0, -5 , 0, 0],
        friends: 0,
        skills: [0, 0, 0, 200, 0, 0],
      },
      {
        level:3,
        nameEs: "Patrullero",
        nameUs: "Patrolman",
        car: {
          image: "",
          name: "",
        },
        salary: 380,
        begintime: 17,
        endtime: 1,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [0, 0, 0, 0, -4, 0, 0],
        friends: 0,
        skills: [0, 0, 0, 200, 0, 0],
      },{
        level:4,
        nameEs: "Sargento en oficinas",
        nameUs: "Desk Sergeant",
        car: {
          image: "",
          name: "",
        },
        salary: 440,
        begintime: 9,
        endtime: 15,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-1, 0, -1, 0, -7, -1, 0],
        friends: 1,
        skills: [0, 200, 0, 200, 0, 0],
      },{
        level:5,
        nameEs: "Antivicio",
        nameUs: "Vice Squad",
        car: {
          image: "",
          name: "",
        },
        salary: 490,
        begintime: 22,
        endtime: 4,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-1, 0, -2, 0, -7, -1, 0],
        friends: 2,
        skills: [0, 300, 0, 400, 0, 0],
      },{
        level:6,
        nameEs: "Detective",
        nameUs: "Detective",
        car: {
          image: "",
          name: "",
        },
        salary: 540,
        begintime: 9,
        endtime: 15,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-2, 0, -3, 0, -8, -2, 0],
        friends: 4,
        skills: [100, 300, 100, 500, 100, 0],
      },{
        level:7,
        nameEs: "Teniente",
        nameUs: "Lieutenant",
        car: {
          image: "",
          name: "",
        },
        salary: 590,
        begintime: 9,
        endtime: 15,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-3, 0, -4, 0, -9, -2, 0],
        friends: 6,
        skills: [100, 300, 200, 500, 300, 100],
      },{
        level:8,
        nameEs: "Jefe de operaciones",
        nameUs: "SWAT Team Leader",
        car: {
          image: "",
          name: "",
        },
        salary: 625,
        begintime: 9,
        endtime: 15,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-3, 0, -5, 0, -9, -3, 0],
        friends: 8,
        skills: [100, 400, 300, 600, 500, 100],
      },{
        level:9,
        nameEs: "Jefe de operaciones",
        nameUs: "Police Chief",
        car: {
          image: "",
          name: "",
        },
        salary: 650,
        begintime: 9,
        endtime: 17,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-3, 0, -4, 0, -7, -2, 0],
        friends: 10,
        skills: [100, 400, 400, 700, 700, 300],
      },{
        level:10,
        nameEs: "Capitán Héroe",
        nameUs: "Captain Hero",
        car: {
          image: "",
          name: "",
        },
        salary: 700,
        begintime: 10,
        endtime: 16,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-3, -13, -7, -4, -10, 0, 0],
        friends: 12,
        skills: [100, 400, 600, 700, 1000, 500],
      },
    ],
  },
  {
    expansion: "Juego Base",
    carrerNameEs: "Criminal",
    carrerNameUs: "Life of Crime",
    levels: [
      {
        level:1,
        nameEs: "Ratero",
        nameUs: "Pickpocket",
        car: {
          image: "",
          name: "",
        },
        salary: 140,
        begintime: 9,
        endtime: 15,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [0, 0, 0, 0, -5, 0, 0],
        friends: 0,
        skills: [0, 0, 0, 0, 0, 0],
      },
      {
        level:2,
        nameEs: "Recadero",
        nameUs: "Bagman",
        car: {
          image: "",
          name: "",
        },
        salary: 200,
        begintime: 23,
        endtime: 7,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [0, 0, 0, 0, -4 , 0, 0],
        friends: 0,
        skills: [0, 0, 0, 0, 0, 0],
      },
      {
        level:3,
        nameEs: "Corredor de apuestas",
        nameUs: "Bookie",
        car: {
          image: "",
          name: "",
        },
        salary: 275,
        begintime: 12,
        endtime: 19,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [0, 0, 0, 0, -5, 0, 0],
        friends: 0,
        skills: [0, 0, 0, 200, 0, 0],
      },{
        level:4,
        nameEs: "Timador",
        nameUs: "Con Artist",
        car: {
          image: "",
          name: "",
        },
        salary: 350,
        begintime: 9,
        endtime: 15,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-1, 0, -1, 0, -7, -1, 0],
        friends: 2,
        skills: [0, 0, 100, 200, 0, 100],
      },{
        level:5,
        nameEs: "Conductor",
        nameUs: "Getaway Driver",
        car: {
          image: "",
          name: "",
        },
        salary: 425,
        begintime: 17,
        endtime: 1,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-1, 0, -1, 0, -5, -1, 0],
        friends: 3,
        skills: [0, 200, 100, 200, 0, 200],
      },{
        level:6,
        nameEs: "Atracador",
        nameUs: "Bank Robber",
        car: {
          image: "",
          name: "",
        },
        salary: 530,
        begintime: 15,
        endtime: 23,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-1, 0, -1, 0, -6, -1, 0],
        friends: 4,
        skills: [0, 300, 200, 300, 100, 200],
      },{
        level:7,
        nameEs: "Revientapisos",
        nameUs: "Cat Burglar",
        car: {
          image: "",
          name: "",
        },
        salary: 640,
        begintime: 21,
        endtime: 3,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-3, 0, -3, 0, -9, -2, -1],
        friends: 6,
        skills: [100, 300, 200, 500, 200, 300],
      },{
        level:8,
        nameEs: "Falsificador",
        nameUs: "Counterfeiter",
        car: {
          image: "",
          name: "",
        },
        salary: 760,
        begintime: 9,
        endtime: 15,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-3, 0, -4, 0, -9, -3, -2],
        friends: 8,
        skills: [100, 500, 200, 500, 300, 500],
      },{
        level:9,
        nameEs: "Contrabandista",
        nameUs: "Smuggler",
        car: {
          image: "",
          name: "",
        },
        salary: 900,
        begintime: 9,
        endtime: 15,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-4, 0, -5, 0, -10, -3, -3],
        friends: 10,
        skills: [100, 500, 500, 600, 300, 600],
      },{
        level:10,
        nameEs: "Cerebro del crimen",
        nameUs: "Criminal Mastermind",
        car: {
          image: "",
          name: "",
        },
        salary: 1100,
        begintime: 18,
        endtime: 0,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-5, 0, -5, 0, -11, -4, -4],
        friends: 12,
        skills: [200, 500, 700, 600, 400, 800],
      },
    ],
  },
];

