//ExpansionShared/ExpansionShared.far/work.iff

//Example
/*worklistExample: {
  work: {
    Expansion: string,
    level_0: {
      Car: {
        img(URL),
        Name(string),
      }
      salary: number,
      begintime: number,
      endtime: number,
      chanceCardEs: string,
      chanceCardEffectEs: string,
      descriptionEs: string,
      promotionEs: string,
      promotionUs: string,
      moodChangesPerHour: [
        Hunger,
        Comfort,
        Higiene,
        Bladder,
        Emergy,
        Fun,
        Social,
      ],
      friends: number,
      skills: [Cooking, Mechanical, Charisma, Body, Logic, Creativity],
    }
    level_1: {
      Car: {
        img(URL),
        Name(string),
      }
      salary: number,
      begintime: number,
      endtime: number,
      chanceCardEs: string,
      chanceCardEffectEs: string,
      descriptionEs: string,
      promotionEs: string,
      promotionUs: string,
      moodChangesPerHour: [
        Hunger,
        Comfort,
        Higiene,
        Bladder,
        Emergy,
        Fun,
        Social,
      ],
      friends: number,
      skills: [Cooking, Mechanical, Charisma, Body, Logic, Creativity],
    }
    level_2: {
      Car: {
        img(URL),
        Name(string),
      }
      salary: number,
      begintime: number,
      endtime: number,
      chanceCardEs: string,
      chanceCardEffectEs: string,
      descriptionEs: string,
      promotionEs: string,
      promotionUs: string,
      moodChangesPerHour: [
        Hunger,
        Comfort,
        Higiene,
        Bladder,
        Emergy,
        Fun,
        Social,
      ],
      friends: number,
      skills: [Cooking, Mechanical, Charisma, Body, Logic, Creativity],
    }
    level_3: {
      Car: {
        img(URL),
        Name(string),
      }
      salary: number,
      begintime: number,
      endtime: number,
      chanceCardEs: string,
      chanceCardEffectEs: string,
      descriptionEs: string,
      promotionEs: string,
      promotionUs: string,
      moodChangesPerHour: [
        Hunger,
        Comfort,
        Higiene,
        Bladder,
        Emergy,
        Fun,
        Social,
      ],
      friends: number,
      skills: [Cooking, Mechanical, Charisma, Body, Logic, Creativity],
    }
    level_4: {
      Car: {
        img(URL),
        Name(string),
      }
      salary: number,
      begintime: number,
      endtime: number,
      chanceCardEs: string,
      chanceCardEffectEs: string,
      descriptionEs: string,
      promotionEs: string,
      promotionUs: string,
      moodChangesPerHour: [
        Hunger,
        Comfort,
        Higiene,
        Bladder,
        Emergy,
        Fun,
        Social,
      ],
      friends: number,
      skills: [Cooking, Mechanical, Charisma, Body, Logic, Creativity],
    }
    level_5: {
      Car: {
        img(URL),
        Name(string),
      }
      salary: number,
      begintime: number,
      endtime: number,
      chanceCardEs: string,
      chanceCardEffectEs: string,
      descriptionEs: string,
      promotionEs: string,
      promotionUs: string,
      moodChangesPerHour: [
        Hunger,
        Comfort,
        Higiene,
        Bladder,
        Emergy,
        Fun,
        Social,
      ],
      friends: number,
      skills: [Cooking, Mechanical, Charisma, Body, Logic, Creativity],
    }
    level_6: {
      Car: {
        img(URL),
        Name(string),
      }
      salary: number,
      begintime: number,
      endtime: number,
      chanceCardEs: string,
      chanceCardEffectEs: string,
      descriptionEs: string,
      promotionEs: string,
      promotionUs: string,
      moodChangesPerHour: [
        Hunger,
        Comfort,
        Higiene,
        Bladder,
        Emergy,
        Fun,
        Social,
      ],
      friends: number,
      skills: [Cooking, Mechanical, Charisma, Body, Logic, Creativity],
    }
    level_7: {
      Car: {
        img(URL),
        Name(string),
      }
      salary: number,
      begintime: number,
      endtime: number,
      chanceCardEs: string,
      chanceCardEffectEs: string,
      descriptionEs: string,
      promotionEs: string,
      promotionUs: string,
      moodChangesPerHour: [
        Hunger,
        Comfort,
        Higiene,
        Bladder,
        Emergy,
        Fun,
        Social,
      ],
      friends: number,
      skills: [Cooking, Mechanical, Charisma, Body, Logic, Creativity],
    }
    level_8: {
      Car: {
        img(URL),
        Name(string),
      }
      salary: number,
      begintime: number,
      endtime: number,
      chanceCardEs: string,
      chanceCardEffectEs: string,
      descriptionEs: string,
      promotionEs: string,
      promotionUs: string,
      moodChangesPerHour: [
        Hunger,
        Comfort,
        Higiene,
        Bladder,
        Emergy,
        Fun,
        Social,
      ],
      friends: number,
      skills: [Cooking, Mechanical, Charisma, Body, Logic, Creativity],
    }
    level_9: {
      Car: {
        img(URL),
        Name(string),
      }
      salary: number,
      begintime: number,
      endtime: number,
      chanceCardEs: string,
      chanceCardEffectEs: string,
      descriptionEs: string,
      promotionEs: string,
      promotionUs: string,
      moodChangesPerHour: [
        Hunger,
        Comfort,
        Higiene,
        Bladder,
        Emergy,
        Fun,
        Social,
      ],
      friends: number,
      skills: [Cooking, Mechanical, Charisma, Body, Logic, Creativity],
    }
  }
}
  */

const worklist = [
  {
    expansion: "Juego Base",
    carrerNameEs: "Negocios",
    carrerNameUs: "Business",
    levels: [
      {
        level: 1,
        nameEs: "Encargado del correo",
        nameUs: "Mailroom Clerk",
        carNameEs: "",
        carNameUs: "Junky",
        salary: 120,
        begintime: 9,
        endtime: 15,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs:
          "Salario mínimo, pero entrarás en una de las megacorporaciones de SimCity. Te tienes que encargar de que la fotocopiadora y la máquina de café funcionen a la perfección. Debes ser organizado, estar disponible, y mostrarte sociable y cordial cuando vayas empujando tu carrito por los pasillos. Puede que algún ejecutivo de la compañía tenga buen ojo y te tenga en cuenta cuando haya una vacante en un puesto superior.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [0, 0, 0, 0, -5, 0, 0],
        friends: 0,
        skills: [0, 0, 0, 0, 0, 0],
      },
      {
        level: 2,
        nameEs: "Ayudante ejecutivo",
        nameUs: "Executive Assistant",
        carNameEs: "",
        carNameUs: "Junky",
        salary: 180,
        begintime: 9,
        endtime: 16,
        chanceCardEs:
          "El jefe ha llegado tarde para hacer un envío importantísimo esta noche. Te has ofrecido a llevar el paquete al aeropuerto. Por tu iniciativa, el jefe te recompensa con una bonificación de 1000 dólares.",
        chanceCardEffectEs: "+§1000",
        descriptionEs:
          "Se trabajan muchas horas, pero tendrás ocasión de ponerte al teléfono, mejorar tu habilidad de trato con la gente, y más ocasiones de complacer al Jefe. Si mejoras tus habilidades mecánicas quizá puedas arreglar la fotocopiadora la próxima vez que ese trasto se averíe. Eso sí que hará que el jefe se fije en ti.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [0, 0, 0, 0, -4, 0, 0],
        friends: 0,
        skills: [0, 0, 0, 0, 0, 0],
      },
      {
        level: 3,
        nameEs: "Representante de ventas",
        nameUs: "Field Sales Rep",
        carNameEs: "",
        carNameUs: "Junky",
        salary: 250,
        begintime: 9,
        endtime: 16,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs:
          "Antes de progresar en la compañía tendrás que ganártelo con muchas horas de carretera. Cumple con tu cupo de ventas (el carisma es imprescindible) y establece contactos, y estarás más cerca de un ascenso que te lleve a un despacho sin ruedas.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [0, 0, 0, 0, -5, 0, 0],
        friends: 0,
        skills: [0, 200, 0, 0, 0, 0],
      },
      {
        level: 4,
        nameEs: "Ejecutivo adjunto",
        nameUs: "Junior Executive",
        carNameEs: "",
        carNameUs: "Default",
        salary: 320,
        begintime: 9,
        endtime: 16,
        chanceCardEs:
          "¡Qué vergüenza! Una copa de ponche de más en la fiesta de la oficina, y has hecho el ridículo más espantoso. Pierdes un punto de carisma.",
        chanceCardEffectEs: "-1 punto de carisma",
        descriptionEs:
          "Ahora tienes esclavos propios a los que tratar a patadas, un cubículo para ti solo, y un sueldo decente... pero aún te queda un largo camino hasta acceder a los cuartos de baño decentes. Mantener buenas relaciones con la gente, y probar tu talento para la lógica, hará que tus superiores se fijen en ti.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-1, 0, -1, 0, -6, -1, 0],
        friends: 1,
        skills: [0, 200, 200, 0, 0, 0],
      },
      {
        level: 5,
        nameEs: "Ejecutivo",
        nameUs: "Executive",
        carNameEs: "",
        carNameUs: "Default",
        salary: 400,
        begintime: 9,
        endtime: 16,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs:
          "Dispones de un ejecutivo adjunto a tus órdenes, y un despacho de los de verdad, con puerta que se cierra y todo. Lo malo es que, en la compañía para la que trabajas, el nivel de ejecutivos está superpoblado. Una mejora en tus habilidades y una buena actitud en el trabajo te ayudarán a destacar entre los demás e impresionar a tus superiores.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-1, 0, -2, 0, -6, -1, 0],
        friends: 3,
        skills: [0, 200, 200, 0, 200, 0],
      },
      {
        level: 6,
        nameEs: "Administrador senior",
        nameUs: "Senior Manager",
        carNameEs: "",
        carNameUs: "Default",
        salary: 520,
        begintime: 9,
        endtime: 16,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs:
          "Tu sueldo se dispara, porque ahora tienes a tu cargo el control de varias franquicias. Hay muchos ejecutivos a tus órdenes, de manera que las habilidades de carisma y lógica te ayudarán a resolver discusiones y a hacer que los diferentes equipos funcionen sin problemas. Tendrás que mejorar tu drive, de ahora en adelante cerrarás muchos tratos en el campo de golf. Así que tampoco estará de más cuidar tu aspecto físico.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-2, 0, -2, 0, -7, -1, 0],
        friends: 6,
        skills: [0, 200, 300, 0, 300, 200],
      },
      {
        level: 7,
        nameEs: "Consejero",
        nameUs: "Vice President",
        carNameEs: "",
        carNameUs: "Town Car",
        salary: 660,
        begintime: 9,
        endtime: 17,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs:
          "Tienes un despacho con vistas a dos calles. Otro aumento de sueldo. Pero la competencia en este piso es muy dura. Sigue cultivando tus habilidades y haz muchos amigos, nunca sabes cuándo los vas a necesitar.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-2, 0, -3, 0, -6, -2, 0],
        friends: 8,
        skills: [0, 200, 400, 200, 400, 200],
      },
      {
        level: 8,
        nameEs: "Vicepresidente",
        nameUs: "President",
        carNameEs: "",
        carNameUs: "Town Car",
        salary: 800,
        begintime: 9,
        endtime: 17,
        chanceCardEs:
          "Con sabiduría y valor, juzgas el caso del gangster más notorio de SimCity y te ganas la admiración de toda la Nación Sim. Te ofrecen un contrato por hacer un libro, con un anticipo de 5000 dólares.",
        chanceCardEffectEs: "+§5000",
        descriptionEs:
          "La compañía manda cada mañana a tu casa un cochazo para recogerte. Tu despacho es una suite en el piso superior, y tu nómina da vértigo. Tu creatividad está al máximo, te sientes el más sagaz, el más poderoso. Pero todo tiene su lado malo: más estrés, y a algunos de tus vecinos no les gustará que tengas tanto éxito (nada que no se arregle con invitarlos a una barbacoa en el jardín de tu casa. Y quién sabe, así quizá conozcas a más gente...)",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-2, 0, -3, 0, -7, -2, 0],
        friends: 10,
        skills: [0, 200, 500, 200, 600, 300],
      },
      {
        level: 9,
        nameEs: "Presidente",
        nameUs: "CEO",
        carNameEs: "",
        carNameUs: "Limo",
        salary: 950,
        begintime: 9,
        endtime: 16,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs:
          "El mandamás de tu compañía. Pero, ¿puede un ejecutivo poderoso y eficaz equilibrar sus responsabilidades en el trabajo con las necesidades de su cónyuge, sus hijos y amigos? Tus responsabilidades sociales crecen, quizá sea hora de que te traslades a una casa más grande para recibir a los figurones como se merecen.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-3, 0, -5, 0, -8, -3, 0],
        friends: 12,
        skills: [0, 200, 600, 200, 700, 500],
      },
      {
        level: 10,
        nameEs: "Magnate",
        nameUs: "Business Tycoon",
        carNameEs: "",
        carNameUs: "Limo",
        salary: 1200,
        begintime: 9,
        endtime: 15,
        chanceCardEs:
          "Estás completamente quemado en tu profesión. En un arranque de inspiración, dejas el mundo de los negocios e inicias una nueva carrera en el deporte. Por fin te van a servir de algo todas las horas que has pasado en el campo de golf. El equipo local te ofrece un puesto como titular, y aceptas.",
        chanceCardEffectEs:
          "Cambio de carrera a Atleta Profesional | nivel 5 - Titular",
        descriptionEs:
          "Eres un empresario agresivo, diriges un conglomerado con oficinas en todo el mundo. Pero, ahora que eres un pilar de la sociedad, ni te lo imaginas... Se espera que hagas donativos para caridad, para mantener tu posición entre tus conciudadanos sims. Pese a los inconvenientes, con éxito la vida es bella.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-5, 0, -6, 0, -11, -4, 0],
        friends: 14,
        skills: [0, 200, 800, 200, 900, 600],
      },
    ],
  },
  {
    expansion: "Juego Base",
    carrerNameEs: "Entretenimiento",
    carrerNameUs: "Entertainment",
    levels: [
      {
        level: 1,
        nameEs: "Camarero",
        nameUs: "Waiter",
        carNameEs: "",
        carNameUs: "Junky",
        salary: 100,
        begintime: 9,
        endtime: 15,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "Tienes tiempo libre para las pruebas, pero por la noche te sacas buenas propinas. Con un poco de don de gentes podrás servir tu foto y tu currículum junto con la ensalada.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [0, 0, 0, 0, -5, 0, 0],
        friends: 0,
        skills: [0, 0, 0, 0, 0, 0],
      },
      {
        level: 2,
        nameEs: "Extra",
        nameUs: "Extra",
        carNameEs: "",
        carNameUs: "Junky",
        salary: 150,
        begintime: 9,
        endtime: 15,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: `Eres "ambiente", "movimiento en el fondo". El sueldo es deleznable, pero al menos estás en el plató. Claro que, no dices nada ni una palabra del guión... y el Departamento de Reparto puede llamarte para el turno o de día o el de noche, depende de las necesidades de la producción. Tienes que desarrollar tu carisma para estar preparado cuando te den unas líneas.`,
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [0, 0, 0, 0, -5, 0, 0],
        friends: 0,
        skills: [0, 0, 0, 0, 0, 0],
      },
      {
        level: 3,
        nameEs: "Figurante",
        nameUs: "Bit Player",
        carNameEs: "",
        carNameUs: "Junky",
        salary: 200,
        begintime: 9,
        endtime: 15,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: `Ya te ganas la vida gracias a tu vocación... por los pelos. Ahora te toca decir algunas frases, que por irónico que parezca a menudo son cosas del tipo "¿Le traigo la carta, señor?" Aquí es muy importante conseguir buenos contactos y mantenerte en forma.`,
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [0, 0, 0, 0, -6, 0, 0],
        friends: 0,
        skills: [0, 0, 200, 0, 0, 0],
      },
      {
        level: 4,
        nameEs: "Especialista de cine",
        nameUs: "Stunt Double",
        carNameEs: "",
        carNameUs: "Default",
        salary: 275,
        begintime: 9,
        endtime: 16,
        chanceCardEs: "¡Aaay! En la escena en que tienes que saltar de un edificio en llamas has caído fuera del colchón. Las lesiones te cuestan dos puntos de físico.",
        chanceCardEffectEs: "-2 puntos de físico",
        descriptionEs: "Ese actor al que prenden fuego antes de tirarlo desde un helicóptero no es la superestrella de la taquilla, eres tú. Pero te estás haciendo un nombre, y a los directores les gustan tus novedosas ideas para imitar la violencia desmandada. Sigue poniendo en práctica tu creatividad. Hasta es posible que consigas el papel protagonista en una película de bajo presupuesto... si sobrevives. Manténte en forma y cuida bien tu equipamiento, o puede que te falle el airbag en el peor momento. Y no descuides tu vida social. No sólo es algo divertido, también puede resultarte muy útil.  ",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-1, 0, -1, 0, -6, -1, 0],
        friends: 2,
        skills: [0, 0, 200, 200, 0, 0],
      },
      {
        level: 5,
        nameEs: "Estrella de series B",
        nameUs: "B-Movie Star",
        carNameEs: "",
        carNameUs: "Default",
        salary: 375,
        begintime: 10,
        endtime: 17,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: `Pelis baratas de ciencia ficción, o con mucha sangre y vísceras, o comedias para adolescentes con hormonas desmadradas. Tú eres la estrella... aunque tus mejores actuaciones vayan "directamente a vídeo" sin pasar por la pantalla grande. Si de verdad aspiras a algo más, necesitas un físico en plena forma, así como diálogos convincentes y creativos. De ahora en adelante casi cualquier progreso te exigira ambas habilidades.`,
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-1, 0, -2, 0, -6, -1, 0],
        friends: 4,
        skills: [0, 0, 300, 300, 0, 100],
      },
      {
        level: 6,
        nameEs: "Secundario",
        nameUs: "Supporting Player",
        carNameEs: "",
        carNameUs: "Limo",
        salary: 500,
        begintime: 10,
        endtime: 18,
        chanceCardEs: `Una agencia importante se ha fijado en ti gracias a tu trabajo en "La novia de la cosa que vino del Planeta X", y te han ofrecido un contrato. ¡Gracias a la fama consigues 2 puntos de carisma!`,
        chanceCardEffectEs: "+2 puntos de carisma",
        descriptionEs: `Tu nombre no aparece en los carteles, pero al menos es una "gran superproducción." Eres el mejor amigo del prota, el secuaz del malo, o el policía que muere en la primera media hora. El caso es que los estudios se han fijado en ti, y hay grandes planes en el horizonte. Sigue ensayando, y recuerda que lo importante no es lo que sabes, sino quién sabe lo que sabes.`,
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-1, 0, -2, 0, -6, -1, 0],
        friends: 6,
        skills: [0, 100, 400, 400, 0, 200],
      },
      {
        level: 7,
        nameEs: "Estrella de la TV",
        nameUs: "TV Star ",
        carNameEs: "",
        carNameUs: "Limo",
        salary: 650,
        begintime: 10,
        endtime: 18,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: `Por fin se reconoce tu talento, y al hablar de ti dicen "La estrella nacida en SimCity". Nunca te había resultado tan fácil organizar una fiesta. Ahora puedes pagarte una casa más grande... pero, con los horarios que tienes, no estarás en ella tanto como te gustaría. Sigue desarrollando tu carisma y tu físico, o no llegarás nunca a la pantalla grande.`,
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-2, 0, -3, 0, -6, -2, 0],
        friends: 8,
        skills: [0, 100, 600, 500, 0, 300],
      },
      {
        level: 8,
        nameEs: "Estrella de Cine",
        nameUs: "Feature Star",
        carNameEs: "",
        carNameUs: "Limo",
        salary: 900,
        begintime: 17,
        endtime: 1,
        chanceCardEs: "La prensa sensacionalista ha descubierto un sucio secreto de tu pasado, y el escándalo es mayúsculo. Te provoca una crisis nerviosa, y tus niveles de habilidad caen en picado.",
        chanceCardEffectEs: "-1 punto de carisma y -1 punto de creatividad",
        descriptionEs: "Lo has conseguido, estás en la pantalla grande. Ahora trabajas menos horas y cobras mucho más, pero a veces de pronto tendrás que salir de la ciudad e ir a rodar a lugares lejanos. De todos modos, disfrutas a fondo de la fama. Todos quieren ser amigos tuyos, pero... ¿eso es siempre bueno? A veces añoras la creatividad espontánea y la respuesta del público en los teatros...",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-2, 0, -3, 0, -7, -2, 0],
        friends: 10,
        skills: [0, 200, 700, 600, 0, 400],
      },
      {
        level: 9,
        nameEs: "Estrella de Teatro",
        nameUs: "Broadway Star",
        carNameEs: "",
        carNameUs: "Limo",
        salary: 1100,
        begintime: 10,
        endtime: 17,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "Es un mundo nuevo para una estrella de la importancia que tienes tú. Actuaciones en directo seis días a la semana, cantar y bailar en el último gran éxito en los musicales de SimCity. ¿Quién imaginaba que iba a ser tan duro en el plano físico? Pero esas fiestas con todo el reparto son una ocasión excepcional para trabar nuevas amistades. ¡Y jamás habías tenido tantos acicates para tu creatividad!",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-3, 0, -5, 0, -8, -3, 0],
        friends: 12,
        skills: [0, 200, 800, 700, 0, 700],
      },
      {
        level: 10,
        nameEs: "Superestrella",
        nameUs: "Superstar",
        carNameEs: "",
        carNameUs: "Limo",
        salary: 1400,
        begintime: 10,
        endtime: 15,
        chanceCardEs: "Has tomado una decisión, ya no te basta con divertir a las masas. Quieres influir de verdad en la sociedad. Tu agente te convence para que aproveches tu poder como estrella y te presentes candidato al Congreso. Ganas las elecciones por mayoría e inicias una nueva carrera en la política.",
        chanceCardEffectEs: "Cambio de carrera a Politica | nivel 7 - Congresista",
        descriptionEs: "Vayas donde vayas, los paparazzi te persiguen. Acaban de poner tu nombre a una de las calles más importantes de SimCity. Y si la fama te empieza a fastidiar, siempre puedes retirarte a tu mansión, desde la que se divisa toda la ciudad.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-6, 0, -8, 0, -13, -5, 0],
        friends: 14,
        skills: [0, 200, 1000, 800, 0, 1000],
      },
    ],
  },
  {
    expansion: "Juego Base",
    carrerNameEs: "Cuerpos de seguridad",
    carrerNameUs: "Law Enforcement",
    levels: [
      {
        level: 1,
        nameEs: "Guardia de seguridad",
        nameUs: "Security Guard",
          carNameEs: "",
          carNameUs: "Squad Car",
        salary: 240,
        begintime: 0,
        endtime: 6,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "Una insignia, un arma... y el turno de noche. Tienes que aportar tu propia arma de fuego y el uniforme corre por tu cuenta, así que el sobre con la paga no te da para mucho.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [0, 0, 0, 0, -5, 0, 0],
        friends: 0,
        skills: [0, 0, 0, 0, 0, 0],
      },
      {
        level: 2,
        nameEs: "Cadete",
        nameUs: "Cadet",
          carNameEs: "",
          carNameUs: "Squad Car",
        salary: 320,
        begintime: 9,
        endtime: 15,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "Asistes a la Academia de Policía, y además con un salario que te da la ciudad y te está quemando en el bolsillo de esos pantalones azules. Es una combinación de campamento militar y universidad, y la experiencia puede resultar extenuante desde el punto de vista físico y mental. Mejora tus aptitudes físicas para poder graduarte y conseguir un empleo de verdad.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [0, 0, 0, 0, -5, 0, 0],
        friends: 0,
        skills: [0, 0, 0, 200, 0, 0],
      },
      {
        level: 3,
        nameEs: "Patrullero",
        nameUs: "Patrolman",
          carNameEs: "",
          carNameUs: "Squad Car",
        salary: 380,
        begintime: 17,
        endtime: 1,
        chanceCardEs: "Has resultado herido en un tiroteo. Pierdes dos puntos de físico, pero ganas uno de carisma.",
        chanceCardEffectEs: "-2 puntos de físico y +1 punto de carisma",
        descriptionEs: "Recorres las peligrosas calles de SimCity en un coche patrulla. El trabajo es peligroso, y la paga buena. Tienes que mantenerte en la mejor forma física y estudiar para mejorar tus aptitudes mecánicas y poder optar a una placa.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [0, 0, 0, 0, -4, 0, 0],
        friends: 0,
        skills: [0, 0, 0, 200, 0, 0],
      },
      {
        level: 4,
        nameEs: "Sargento en oficinas",
        nameUs: "Desk Sergeant",
          carNameEs: "",
          carNameUs: "Squad Car",
        salary: 440,
        begintime: 9,
        endtime: 15,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "Una pausa en tu vida tras una temporada en las duras calles. Se trata de un ascenso, la paga es mejor, pero el papeleo te abruma. Lo mejor es que tienes un horario fijo, y ya no dependes tanto de tu forma física. Si te cansas de este empleo burocrático, mejora tus aptitudes físicas y mecánicas, y quizá vuelvas a salir a las calles, aunque en un puesto mucho más interesante...",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-1, 0, -1, 0, -7, -1, 0],
        friends: 1,
        skills: [0, 200, 0, 200, 0, 0],
      },
      {
        level: 5,
        nameEs: "Antivicio",
        nameUs: "Vice Squad",
          carNameEs: "",
          carNameUs: "Squad Car",
        salary: 490,
        begintime: 22,
        endtime: 4,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: `Es tu primer trabajo "de paisano". El trabajo en antivicio suele ser emocionante, pero tu grupo opera a menudo de noche. Es importante destacar en este puesto para que te tengan en cuenta a la hora de los ascensos al rango de detective. Necesitarás cultivar tus habilidades, especialmente la lógica, para conseguir un ascenso más rápido.`,
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-1, 0, -2, 0, -7, -1, 0],
        friends: 2,
        skills: [0, 300, 0, 400, 0, 0],
      },
      {
        level: 6,
        nameEs: "Detective",
        nameUs: "Detective",
          carNameEs: "",
          carNameUs: "Squad Car",
        salary: 540,
        begintime: 9,
        endtime: 15,
        chanceCardEs: "Una editorial de tebeos ha decidido hacer una serie en la que eres el protagonista. Tu agente te negocia un anticipo de 5000 dólares y tu carisma se dispara por las nubes. ",
        chanceCardEffectEs: "+§5000",
        descriptionEs: "Ya tienes placa, y sigues de paisano. Necesitas de una lógica excepcional y muchos amigos. También cuenta mucho el carisma, sobre todo cuando los sospechosos e informantes sean importantes para cerrar casos y ascender por los escalafones del Departamento.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-2, 0, -3, 0, -8, -2, 0],
        friends: 4,
        skills: [100, 300, 100, 500, 100, 0],
      },
      {
        level: 7,
        nameEs: "Teniente",
        nameUs: "Lieutenant",
          carNameEs: "",
          carNameUs: "Limo",
        salary: 590,
        begintime: 9,
        endtime: 15,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: `Te corresponden casos más importantes, y gracias a tu experiencia has conseguido un salario mucho mejor. Como teniente, eres jefe de un equipo de detectives, y necesitarás de todas tus habilidades. Lo malo es que las presiones que te impone el nutrido archivo de casos no resueltos en SimCity puede afectar a tu vida privada. Intenta prestar atención a la "vida familiar" y al ocio cuando estés en casa, para obtener el equilibrio adecuado.`,
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-3, 0, -4, 0, -9, -2, 0],
        friends: 6,
        skills: [100, 300, 200, 500, 300, 100],
      },
      {
        level: 8,
        nameEs: "Jefe de operaciones especiales",
        nameUs: "SWAT Team Leader",
          carNameEs: "",
          carNameUs: "Limo",
        salary: 625,
        begintime: 9,
        endtime: 15,
        chanceCardEs: "Tu grupo ha rescatado un autobús lleno de niños de manos de terroristas urbanos. Una revista nacional te paga 4000 dólares por una entrevista en exclusiva.",
        chanceCardEffectEs: "+§4000",
        descriptionEs: "Es un trabajo de élite, con importantes bonificaciones por peligrosidad. Pero aquí el éxito exige buenas dosis de agudeza y creatividad. Asegúrate de contar con buenos amigos en puestos altos.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-3, 0, -5, 0, -9, -3, 0],
        friends: 8,
        skills: [100, 400, 300, 600, 500, 100],
      },
      {
        level: 9,
        nameEs: "Jefe de policía",
        nameUs: "Police Chief",
          carNameEs: "",
          carNameUs: "Limo",
        salary: 650,
        begintime: 9,
        endtime: 17,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "Por fin eres el mandamás del Departamento. Te puedes permitir una hermosa casa en lo mejor de la ciudad. ¿Qué más puedes hacer para proteger a los ciudadanos de SimCity.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-3, 0, -4, 0, -7, -2, 0],
        friends: 10,
        skills: [100, 400, 400, 700, 700, 300],
      },
      {
        level: 10,
        nameEs: "Capitán Héroe",
        nameUs: "Captain Hero",
          carNameEs: "",
          carNameUs: "Limo",
        salary: 700,
        begintime: 10,
        endtime: 16,
        chanceCardEs: `Tus hazañas te han hecho famoso en toda la ciudad. Te han ofrecido el papel protagonista en una nueva serie de televisión, "Las aventuras del Capitán Héroe". El mundo del espectáculo te llama, así que cambias de profesión.`,
        chanceCardEffectEs: "Cambio de carrera a Entretenimiento | nivel 7 - Estrella de la TV",
        descriptionEs: "¡Temblad, criminales! Amanece un nuevo día en nuestra hermosa ciudad. Un día de justicia, ¡al fin ha llegado el Capitán Héroe! Con sus superpoderes, el Capitán Héroe combate el crimen día a día, velando por el cumplimiento de la ley.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-3, -13, -7, -4, -10, 0, 0],
        friends: 12,
        skills: [100, 400, 600, 700, 1000, 500],
      },
    ],
  },
  {
    expansion: "Juego Base",
    carrerNameEs: "Criminal",
    carrerNameUs: "Life of Crime",
    levels: [
      {
        level: 1,
        nameEs: "Ratero",
        nameUs: "Pickpocket",
          carNameEs: "",
          carNameUs: "Junky",
        salary: 140,
        begintime: 9,
        endtime: 15,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: `Eres un ladronzuelo de tercera... pero nadie te da órdenes. Evidentemente, la destreza y la velocidad física son vitales. Tampoco te irá mal cierto nivel de carisma, si quieres meterte en el bolsillo a tus "clientes" antes de meter mano a sus bolsillos.`,
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [0, 0, 0, 0, -5, 0, 0],
        friends: 0,
        skills: [0, 0, 0, 0, 0, 0],
      },
      {
        level: 2,
        nameEs: "Recadero",
        nameUs: "Bagman",
          carNameEs: "",
          carNameUs: "Junky",
        salary: 200,
        begintime: 23,
        endtime: 7,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: `Eres el chico de los recados para un gángster de medio pelo. Te encargas de la recogida y entrega del dinero sucio y "mercancía discreta". Tendrás que ser rápido para esquivar a la pasma y a las bandas rivales. Trabaja tus habilidades físicas, te serán imprescindibles.`,
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [0, 0, 0, 0, -4, 0, 0],
        friends: 0,
        skills: [0, 0, 0, 0, 0, 0],
      },
      {
        level: 3,
        nameEs: "Corredor de apuestas",
        nameUs: "Bookie",
          carNameEs: "",
          carNameUs: "Default",
        salary: 275,
        begintime: 12,
        endtime: 19,
        chanceCardEs: "¡Es tu día de suerte! No ha habido ganadores. Te embolsas 2000 dólares.",
        chanceCardEffectEs: "+§2000",
        descriptionEs: `Haz apuestas en el canódromo, las carreras de caballos, y los eventos deportivos, donde de una forma u otra, "la casa" siempre gana. Y esta vez la casa eres tú. Sabes cuando algo puede ir mal se necesita dialogar para mantener el carisma y la creatividad en forma.`,
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [0, 0, 0, 0, -5, 0, 0],
        friends: 0,
        skills: [0, 0, 0, 200, 0, 0],
      },
      {
        level: 4,
        nameEs: "Timador",
        nameUs: "Con Artist",
          carNameEs: "",
          carNameUs: "Default",
        salary: 350,
        begintime: 9,
        endtime: 15,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "Planifica y lleva a cabo estafas, timos y fraudes, lo que sea con tal de quitarle a un sim ingenuo su dinero. Tus ganancias aumentan, pero para este trabajo hace falta pensar deprisa y tener una buena capacidad de persuasión.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-1, 0, -1, 0, -7, -1, 0],
        friends: 2,
        skills: [0, 0, 100, 200, 0, 100],
      },
      {
        level: 5,
        nameEs: "Conductor",
        nameUs: "Getaway Driver",
          carNameEs: "",
          carNameUs: "Default",
        salary: 425,
        begintime: 17,
        endtime: 1,
        chanceCardEs: "¡Vaya con el as del volante! Has chocado contra la camioneta de un repartidor de helados. Las reparaciones y la vainilla fundida te cuestan 2000 dólares.",
        chanceCardEffectEs: "-§1000",
        descriptionEs: "De criminal de medio pelo a criminal de pelo entero. Para tener éxito en la profesión de conducir coches para las fugas tendrás que estar muy en forma, y contar con amplios conocimientos de mecánica. Pero quieres estar en el centro de la acción, ¿no? Pues esmérate para demostrarle al jefe que eres imprescindible.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-1, 0, -1, 0, -5, -1, 0],
        friends: 3,
        skills: [0, 200, 100, 200, 0, 200],
      },
      {
        level: 6,
        nameEs: "Atracador",
        nameUs: "Bank Robber",
          carNameEs: "",
          carNameUs: "Town Car",
        salary: 530,
        begintime: 15,
        endtime: 23,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: `Ya no te limitas a conducir el coche donde va el dinero, ahora estás dentro del Banco Nacional de SimCity para "recogerlo", así que te corresponde una tajada mayor. Pero te gustaría probar con crímenes más "escurridizos", que presenten un desafío mayor. Para ascender necesitas cerebro, coraje y colegas.`,
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-1, 0, -1, 0, -6, -1, 0],
        friends: 4,
        skills: [0, 300, 200, 300, 100, 200],
      },
      {
        level: 7,
        nameEs: "Revientapisos",
        nameUs: "Cat Burglar",
          carNameEs: "",
          carNameUs: "Town Car",
        salary: 640,
        begintime: 21,
        endtime: 3,
        chanceCardEs: "En el Museo de SimCity hay una exposición de las fabulosas Joyas de los Zares. Mejor dicho, la había. Ahora las piedras viajan en dirección a un tallador de gemas de El Cairo, y te han dejado un beneficio de 6000 dólares.",
        chanceCardEffectEs: "+§6000",
        descriptionEs: "Las ganancias son mayores, pero el riesgo también. De pronto te encuentras siempre trabajando en el turno de noche. No te puedes permitir el lujo de descuidar tu físico, en este trabajo es imprescindible estar en plena forma. También necesitarás habilidades mecánicas para mantener tus herramientas en perfecto estado, y una buena capacidad creativa a la hora de resolver problemas te ayudará a esquivar la cárcel. También necesitarás de la ayuda de tus amigos.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-3, 0, -3, 0, -9, -2, -1],
        friends: 6,
        skills: [100, 300, 200, 500, 200, 300],
      },
      {
        level: 8,
        nameEs: "Falsificador",
        nameUs: "Counterfeiter",
          carNameEs: "",
          carNameUs: "Town Car",
        salary: 760,
        begintime: 9,
        endtime: 15,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "Tu nivel de sofisticación sube por momentos. ¿Para qué robar dinero, si tu banda y tú podéis imprimir tanto como queráis? Te has labrado toda una reputación, la gente te busca para pedirte consejo. Debes practicar tu carisma y creatividad, por si se presenta la ocasión de saltar a la escena internacional.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-3, 0, -4, 0, -9, -3, -2],
        friends: 8,
        skills: [100, 500, 200, 500, 300, 500],
      },
      {
        level: 9,
        nameEs: "Contrabandista",
        nameUs: "Smuggler",
          carNameEs: "",
          carNameUs: "Town Car",
        salary: 900,
        begintime: 9,
        endtime: 15,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: `Según tu tarjeta de visita, te dedicas a "Importaciones/Exportaciones". También se podría decir que proporcionas a la gente lo que la gente quiere y la ley le impide tener. Traes y llevas mercancías por tierra, mar y aire, con los enormes beneficios que ello implica. Todas tus habilidades deberán estar al máximo para llegar a la cumbre en esta ilustre profesión.`,
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-4, 0, -5, 0, -10, -3, -3],
        friends: 10,
        skills: [100, 500, 500, 600, 300, 600],
      },
      {
        level: 10,
        nameEs: "Cerebro del crimen",
        nameUs: "Criminal Mastermind",
          carNameEs: "",
          carNameUs: "Limo",
        salary: 1100,
        begintime: 18,
        endtime: 0,
        chanceCardEs: `Tras varios minutos de autoanálisis decides por fin volver al buen camino. Tu primo segundo te busca un puesto legal en una compañía de seguros importante. Tu experiencia previa en las "recuperaciones" te será de gran utilidad. Ahora eres un "verdadero" hombre de negocios.`,
        chanceCardEffectEs: "Cambio de carrera a Hacker | nivel 5 - Asesor de seguridad",
        descriptionEs: "Hay pocos hombres que no te teman. Diriges tu propia organización de ladrones y criminales de alto nivel, y puedes permitirte el lujo de comprar cualquier casa de la manzana. Tu fachada es un respetable negocio en SimCity, y casi te sientes por encima de la ley.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-5, 0, -5, 0, -11, -4, -4],
        friends: 12,
        skills: [200, 500, 700, 600, 400, 800],
      },
    ],
  },
  {
    expansion: "Juego Base",
    carrerNameEs: "Medicina",
    carrerNameUs: "Medicine",
    levels: [
      {
        level: 1,
        nameEs: "Auxiliar clínico",
        nameUs: "Medical Technician",
        carNameEs: "",
        carNameUs: "Junky",
        salary: 200,
        begintime: 9,
        endtime: 15,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "El nivel más bajo y un salario de esclavo en un gran laboratorio médico... pero es una buena manera de probar tu aptitud e interés en el mundo de la medicina. Te encargarás de tomar placas de rayos-x, recoger información sobre las muestras, preparar los resultados de las pruebas, y otras muchas cosas.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [0, 0, 0, 0, -5, 0, 0],
        friends: 0,
        skills: [0, 0, 0, 0, 0, 0],
      },
      {
        level: 2,
        nameEs: "Paramédico",
        nameUs: "Paramedic",
        carNameEs: "",
        carNameUs: "Junky",
        salary: 275,
        begintime: 23,
        endtime: 5,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "Vas a clases de medicina, y trabajas como paramédico a tiempo parcial. Tendrás que evitar el exceso de fatiga, y a la vez sacar tiempo para estudiar e ir en las ambulancias en el turno de noche. Mantén a punto tu vehículo y el equipamiento, refuerza tanto como puedas tus habilidades mecánicas.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [0, 0, 0, 0, -5, 0, 0],
        friends: 0,
        skills: [0, 0, 0, 0, 0, 0],
      },
      {
        level: 3,
        nameEs: "Enfermero",
        nameUs: "Nurse",
        carNameEs: "",
        carNameUs: "Default",
        salary: 340,
        begintime: 9,
        endtime: 15,
        chanceCardEs: "Has llevado demasiado lejos tu trato personal con el paciente, y te salpica un escándalo hospitalario. Tu carisma se dispara... pero te ponen una multa de 500 dólares.",
        chanceCardEffectEs: "-§500 y +1 punto de carisma",
        descriptionEs: "Te has graduado en la escuela de medicina, y ya tienes tu primer empleo en el Hospital General Sim. Es un trabajo muy duro en el aspecto físico, exige que estés en buenas condiciones. Sé amable y cariñoso con los pacientes para que hablen bien de ti.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [0, 0, 0, 0, -6, 0, 0],
        friends: 0,
        skills: [0, 200, 0, 0, 0, 0],
      },
      {
        level: 4,
        nameEs: "Interno",
        nameUs: "Intern",
        carNameEs: "",
        carNameUs: "Default",
        salary: 410,
        begintime: 9,
        endtime: 18,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: `Ahora te llaman "doctor", pero te da la sensación de que te pasas más tiempo rellenando papeles y cambiando vendas que salvando vidas. Presta especial atención al desarrollo de tus habilidades mecánicas y lógicas; un médico necesita capacidades muy diversas. Por lo menos tienes un trabajo permanente, y por supuesto ganas más..`,
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [0, 0, -1, 0, -4, 0, 0],
        friends: 2,
        skills: [0, 200, 0, 200, 0, 0],
      },
      {
        level: 5,
        nameEs: "Residente",
        nameUs: "Resident",
        carNameEs: "",
        carNameUs: "Default",
        salary: 480,
        begintime: 21,
        endtime: 4,
        chanceCardEs: `Hollywood te llama: un productor te ofrece un contrato a cambio de tu asesoría en la popular serie "Hospital SimCity". Recibes un anticipo de 2000 dólares por tus servicios.`,
        chanceCardEffectEs: "+§2000",
        descriptionEs: "Te han ascendido y ahora estás como médico residente en el turno de noche de la sala de urgencias. El puesto conlleva, obviamente, un gran estrés, así que necesitas un hogar donde estés realmente cómodo. También te hará falta algo de diversión, descanso y comer de manera adecuada, o no alcanzarás el éxito. Acierta en los diagnósticos, presta especial atención a los casos difíciles, y trata bien a tus pacientes. Tu ascenso a la medicina general está a la vuelta de la esquina.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-1, 0, -2, 0, -6, -1, 0],
        friends: 3,
        skills: [0, 300, 0, 200, 200, 0],
      },
      {
        level: 6,
        nameEs: "Medicina general",
        nameUs: "GP",
        carNameEs: "Coche Deportivo",
        carNameUs: "Town Car",
        salary: 550,
        begintime: 10,
        endtime: 18,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "Esa vena altruista que tienes te ha impulsado a trabajar en un ambulatorio de barrio, en la medicina general. El sueldo no es muy alto, pero tendrás ocasión de ayudar a tus conciudadanos menos afortunados con sus huesos rotos, embarazos y sarampiones. Tendrás que cargar con mucho trabajo, pero no dejes de cultivar tus habilidades. Algún día puedes querer aspirar a otro tipo de trabajo.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-1, 0, -2, 0, -6, -1, 0],
        friends: 4,
        skills: [0, 300, 100, 300, 400, 0],
      },
      {
        level: 7,
        nameEs: "Especialista",
        nameUs: "Specialist",
        carNameEs: "Coche Deportivo",
        carNameUs: "Town Car",
        salary: 625,
        begintime: 10,
        endtime: 16,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "Felicidades. Ya tienes tu propia consulta, con el tradicional calendario de trabajo que siempre deja tiempo para jugar al golf. Ahora tienes más tiempo para dedicar a tu hogar, ¿y tal vez para tener una familia feliz? Sigue practicando tu carisma si quieres ascender en esta rama profesional.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-3, 0, -4, 0, -9, -2, 0],
        friends: 5,
        skills: [0, 400, 200, 400, 400, 100],
      },
      {
        level: 8,
        nameEs: "Cirujano",
        nameUs: "Surgeon",
        carNameEs: "Coche Deportivo",
        carNameUs: "Town Car",
        salary: 700,
        begintime: 10,
        endtime: 16,
        chanceCardEs: "",
        chanceCardEffectEs: "",
        descriptionEs: "Ahora estás en la élite, y se nota en tu salario. Para este trabajo sólo sirve gente descansada y tranquila, así que controla tus niveles emocionales, come bien y duerme lo necesario. También tendrás que sacar tiempo para estudiar en casa y mantener en forma el hemisferio izquierdo de tu cerebro, que es el que se encarga de la lógica. Mejora tu creatividad tanto como puedas.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-3, 0, -5, 0, -9, -3, 0],
        friends: 7,
        skills: [0, 400, 300, 500, 600, 200],
      },
      {
        level: 9,
        nameEs: "Investigador médico",
        nameUs: "Medical Researcher",
        carNameEs: "Limusina Negra",
        carNameUs: "Limo",
        salary: 775,
        begintime: 9,
        endtime: 16,
        chanceCardEs: "¡Has creado una nueva vacuna, la Virulux! Los derechos de la patente te reportan unos beneficios de 8000 dólares, y tu carisma mejora.",
        chanceCardEffectEs: "+§2000 y +1 punto de carisma",
        descriptionEs: "Has creado un nuevo suero vacuna en los laboratorios de investigación médica más avanzados de SimCity, y estás entre los investigadores mejor pagados del mundo. Si aún quieres más pasta, sigue cultivando tus habilidades para llegar a director de hospital, puesto en el que tendrás un porcentaje sobre los beneficios.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-3, 0, -5, 0, -8, -3, 0],
        friends: 9,
        skills: [0, 500, 400, 600, 800, 300],
      },
      {
        level: 10,
        nameEs: "Director de hospital",
        nameUs: "Chief of Hospital Staff",
        carNameEs: "Limusina Negra",
        carNameUs: "Limo",
        salary: 850,
        begintime: 9,
        endtime: 16,
        chanceCardEs: "La rutina diaria de la dirección del hospital te está consumiendo. Tras mucho soñar con nuevos desafíos, decides por fin poner manos a la obra. Dimites de tu puesto e inicias una nueva carrera en el mundo de la ciencia. Tu experiencia médica te permite arrancar desde el avanzado nivel de inventor.",
        chanceCardEffectEs: "Cambio de carrera a Ciencia | nivel 6 - Inventor",
        descriptionEs: "Eres uno de los médicos más respetados de SimCity. Te pasas las horas laborales en tu despacho del hospital, que ahora en parte te pertenece, y sacas buenos beneficios al tiempo que mantienes con buena salud a tus conciudadanos.",
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-4, 0, -5, 0, -9, -3, 0],
        friends: 11,
        skills: [0, 600, 600, 700, 900, 400],
      },
    ],
  },{
    expansion: "Juego Base",
    carrerNameEs: "Ejército",
    carrerNameUs: "Military",
    levels: [
      {
        level: 1,
        nameEs: "Recluta",
        nameUs: "Recruit",
        carNameEs: "",
        carNameUs: "Military Jeep",
        salary: 250,
        begintime: 6,
        endtime: 12,
        chanceCardEs: ``,
        chanceCardEffectEs: "",
        descriptionEs: `El pelo al cero y el entrenamiento duro. Y limpiar letrinas no es precisamente un trabajo agradable. Tendrás que estar en la mejor forma física para salir de las trincheras. No sólo estarás más fuerte, también te sentará mejor el uniforme.`,
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [0, 0, -2, 0, -5, 0, 0],
        friends: 0,
        skills: [0, 0, 0, 0, 0, 0],
      },
      {
        level: 2,
        nameEs: "Fuerzas de élite",
        nameUs: "Elite Forces",
        carNameEs: "",
        carNameUs: "Military Jeep",
        salary: 325,
        begintime: 7,
        endtime: 13,
        chanceCardEs: `Una espantosa semana de maniobras se cobra un precio elevado. Pierdes un punto de físico.`,
        chanceCardEffectEs: "-1 punto de físico",
        descriptionEs: `El entrenamiento especial como comando te da mayor prestigio y además tendrás un incentivo por peligrosidad. Las habilidades físicas tienen gran importancia para mantener tu cuerpo en plena forma.`,
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [0, 0, -2, 0, -5, 0, 0],
        friends: 0,
        skills: [0, 0, 0, 0, 0, 0],
      },
      {
        level: 3,
        nameEs: "Instructor",
        nameUs: "Drill Instructor",
        carNameEs: "",
        carNameUs: "Military Jeep",
        salary: 400,
        begintime: 8,
        endtime: 14,
        chanceCardEs: ``,
        chanceCardEffectEs: "",
        descriptionEs: `Ahora que eres un veterano con experiencia, el comandante de la base te ha presentado "voluntario" para impartir tus conocimientos a un escuadrón de reclutas muy verdes y muy maleables. Aquí el carisma es vital, porque tendrás que imbuir miedo, lealtad y disciplina en muchos pelados.`,
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [0, 0, -3, 0, -6, 0, 0],
        friends: 0,
        skills: [0, 0, 0, 200, 0, 0],
      },
      {
        level: 4,
        nameEs: "Oficial",
        nameUs: "Junior Officer",
        carNameEs: "",
        carNameUs: "Military Jeep",
        salary: 450,
        begintime: 9,
        endtime: 15,
        chanceCardEs: `Bajo tu dirección, tu escuadrón nocturno se filtra tras las líneas enemigas y se apodera de su cuartel general para ganar la competición para tu división. Su creatividad y tu carisma mejoran.`,
        chanceCardEffectEs: "+1 punto de carisma y +1 punto de creativo",
        descriptionEs: `Por fin tienes acceso al club de oficiales. Pero no te duermas en los laureles, tendrás que mantenerte en óptimas condiciones físicas si quieres progresar.`,
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-1, 0, -3, 0, -7, -1, 0],
        friends: 0,
        skills: [0, 100, 200, 200, 0, 0],
      },
      {
        level: 5,
        nameEs: "Contra-inteligencia",
        nameUs: "Counter-Intelligence",
        carNameEs: "",
        carNameUs: "Military Jeep",
        salary: 500,
        begintime: 9,
        endtime: 15,
        chanceCardEs: ``,
        chanceCardEffectEs: "",
        descriptionEs: `Ahora dedicas tu vida a seguir la pista del enemigo utilizando el equipamiento más moderno. Sabes tanto de su estrategia que te has convertido en un blanco tentador para ellos... así que, por tu bien y el de tus soldados, no te descuides ni un momento. Ejercita tus aptitudes mecánicas para mantener en buen funcionamiento esas máquinas tan delicadas, y agudiza tu lógica para interpretar todos los datos que te llegan.`,
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-1, 0, -4, 0, -7, -2, 0],
        friends: 0,
        skills: [100, 100, 200, 400, 0, 0],
      },
      {
        level: 6,
        nameEs: "Oficial de vuelo",
        nameUs: "Flight Officer",
        carNameEs: "",
        carNameUs: "Military Jeep",
        salary: 550,
        begintime: 9,
        endtime: 15,
        chanceCardEs: ``,
        chanceCardEffectEs: "",
        descriptionEs: `Alguien tiene que pilotar el avión que lleva a los soldados, transportar el cargamento y vigilar el espacio aéreo sobre SimCity. En este nivel el sueldo es mejor, pero para ganarte las alas tendrás que entrenarte en el simulador de vuelo de la base. La habilidad mecánica es imprescindible, y la lógica no se queda atrás.`,
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-2, 0, -4, 0, -8, -2, 0],
        friends: 1,
        skills: [100, 200, 400, 400, 100, 0],
      },
      {
        level: 7,
        nameEs: "Oficial superior",
        nameUs: "Senior Officer",
        carNameEs: "",
        carNameUs: "Military Jeep",
        salary: 580,
        begintime: 9,
        endtime: 15,
        chanceCardEs: ``,
        chanceCardEffectEs: "",
        descriptionEs: `Has sobrevivido al servicio en el aire, y ahora estás entre los mandamases. Eres un militar muy respetado, y muchos te piden consejo. Sigue ejercitando la lógica para ser un estratega aún mejor, y un poco de carisma te ayudará a mejorar tus discursos. Si quieres llegar a comandante, trabaja estos aspectos.`,
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-3, 0, -5, 0, -9, -3, 0],
        friends: 3,
        skills: [100, 300, 400, 500, 300, 0],
      },
      {
        level: 8,
        nameEs: "Comandante",
        nameUs: "Commander",
        carNameEs: "",
        carNameUs: "Military Jeep",
        salary: 600,
        begintime: 9,
        endtime: 15,
        chanceCardEs: ``,
        chanceCardEffectEs: "",
        descriptionEs: `Tus logros en cuestión de liderazgo te han ganado el rango de comandante. Se acabó lo de esquivar balas y arrastrarte bajo alambre de púas. Pero no engordes, se rumorea que tu nombre está entre los que se barajan como candidato a astronauta. Para conseguir ese honor tendrás que demostrar aptitudes físicas y mecánicas excepcionales.`,
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-3, 0, -5, 0, -10, -4, 0],
        friends: 5,
        skills: [100, 600, 500, 500, 500, 0],
      },
      {
        level: 9,
        nameEs: "Astronauta",
        nameUs: "Astronaut",
        carNameEs: "",
        carNameUs: "Limo",
        salary: 625,
        begintime: 9,
        endtime: 15,
        chanceCardEs: `Te han seleccionado para entrenar a la primera misión tripulada a Marte. Tu carisma se pone por las nubes y recibes una bonificación de 5000 dólares.`,
        chanceCardEffectEs: "+§5000 y +2 puntos de carisma",
        descriptionEs: `Uno de los mayores logros para un militar profesional como tú. Cada misión al espacio te da más fama y fortuna, y jamás has estado en mejor forma física. Sigue ejercitando tus aptitudes si quieres convertirte en una de las personas más influyentes del país.`,
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-4, 0, -5, 0, -10, -5, 0],
        friends: 6,
        skills: [100, 900, 500, 800, 600, 0],
      },
      {
        level: 10,
        nameEs: "General",
        nameUs: "General",
        carNameEs: "",
        carNameUs: "Staff Sedan",
        salary: 650,
        begintime: 9,
        endtime: 15,
        chanceCardEs: `La reducción de personal en el ejército te ha forzado a un retiro prematuro. La verdad es que no te gusta pescar, así que buscas un trabajo en el cuerpo policial como jefe de operaciones especiales. Tus profundos conocimientos de estrategia y tácticas te serán muy útiles.`,
        chanceCardEffectEs: "Cambio de carrera a Cuerpos de seguridad | nivel 8 - Jefe de operaciones especiales",
        descriptionEs: `Tu talento logístico te ha llevado al rango de general, el que más manda de entre los mandamases. Te pasas el día entre agentes gubernamentales que piden tus sabios consejos, y te han hecho una oferta muy apetecible por tus memorias. ¿Es tu vida familiar tan perfecta como la profesional?`,
        promotionEs: "",
        promotionUs: "",
        moodChangesPerHour: [-5, 0, -6, 0, -11, -5, 0],
        friends: 8,
        skills: [100, 1000, 700, 1000, 900, 0],
      },
    ],
  }
];

const newwork = {
  expansion: "Juego Base",
  carrerNameEs: "",
  carrerNameUs: "",
  levels: [
    {
      level: 1,
      nameEs: "",
      nameUs: "",
      carNameEs: "",
      carNameUs: "",
      salary: 0,
      begintime: 0,
      endtime: 0,
      chanceCardEs: ``,
      chanceCardEffectEs: "",
      descriptionEs: ``,
      promotionEs: "",
      promotionUs: "",
      moodChangesPerHour: [0, 0, 0, 0, -5, 0, 0],
      friends: 0,
      skills: [0, 0, 0, 0, 0, 0],
    },
    {
      level: 2,
      nameEs: "",
      nameUs: "",
      carNameEs: "",
      carNameUs: "",
      salary: 0,
      begintime: 0,
      endtime: 0,
      chanceCardEs: ``,
      chanceCardEffectEs: "",
      descriptionEs: ``,
      promotionEs: "",
      promotionUs: "",
      moodChangesPerHour: [0, 0, 0, 0, -4, 0, 0],
      friends: 0,
      skills: [0, 0, 0, 0, 0, 0],
    },
    {
      level: 3,
      nameEs: "",
      nameUs: "",
      carNameEs: "",
      carNameUs: "",
      salary: 0,
      begintime: 0,
      endtime: 0,
      chanceCardEs: ``,
      chanceCardEffectEs: "",
      descriptionEs: ``,
      promotionEs: "",
      promotionUs: "",
      moodChangesPerHour: [0, 0, 0, 0, -5, 0, 0],
      friends: 0,
      skills: [0, 0, 0, 0, 0, 0],
    },
    {
      level: 4,
      nameEs: "",
      nameUs: "",
      carNameEs: "",
      carNameUs: "",
      salary: 0,
      begintime: 0,
      endtime: 0,
      chanceCardEs: ``,
      chanceCardEffectEs: "",
      descriptionEs: ``,
      promotionEs: "",
      promotionUs: "",
      moodChangesPerHour: [0, 0, 0, 0, 0, 0, 0],
      friends: 0,
      skills: [0, 0, 0, 0, 0, 0],
    },
    {
      level: 5,
      nameEs: "",
      nameUs: "",
      carNameEs: "",
      carNameUs: "",
      salary: 0,
      begintime: 0,
      endtime: 0,
      chanceCardEs: ``,
      chanceCardEffectEs: "",
      descriptionEs: ``,
      promotionEs: "",
      promotionUs: "",
      moodChangesPerHour: [0, 0, 0, 0, 0, 0, 0],
      friends: 0,
      skills: [0, 0, 0, 0, 0, 0],
    },
    {
      level: 6,
      nameEs: "",
      nameUs: "",
      carNameEs: "",
      carNameUs: "",
      salary: 0,
      begintime: 0,
      endtime: 0,
      chanceCardEs: ``,
      chanceCardEffectEs: "",
      descriptionEs: ``,
      promotionEs: "",
      promotionUs: "",
      moodChangesPerHour: [0, 0, 0, 0, 0, 0, 0],
      friends: 0,
      skills: [0, 0, 0, 0, 0, 0],
    },
    {
      level: 7,
      nameEs: "",
      nameUs: "",
      carNameEs: "",
      carNameUs: "",
      salary: 0,
      begintime: 0,
      endtime: 0,
      chanceCardEs: ``,
      chanceCardEffectEs: "",
      descriptionEs: ``,
      promotionEs: "",
      promotionUs: "",
      moodChangesPerHour: [0, 0, 0, 0, 0, 0, 0],
      friends: 0,
      skills: [0, 0, 0, 0, 0, 0],
    },
    {
      level: 8,
      nameEs: "",
      nameUs: "",
      carNameEs: "",
      carNameUs: "",
      salary: 0,
      begintime: 0,
      endtime: 0,
      chanceCardEs: ``,
      chanceCardEffectEs: "",
      descriptionEs: ``,
      promotionEs: "",
      promotionUs: "",
      moodChangesPerHour: [0, 0, 0, 0, 0, 0, 0],
      friends: 0,
      skills: [0, 0, 0, 0, 0, 0],
    },
    {
      level: 9,
      nameEs: "",
      nameUs: "",
      carNameEs: "",
      carNameUs: "",
      salary: 0,
      begintime: 0,
      endtime: 0,
      chanceCardEs: ``,
      chanceCardEffectEs: "",
      descriptionEs: ``,
      promotionEs: "",
      promotionUs: "",
      moodChangesPerHour: [0, 0, 0, 0, 0, 0, 0],
      friends: 0,
      skills: [0, 0, 0, 0, 0, 0],
    },
    {
      level: 10,
      nameEs: "",
      nameUs: "",
      carNameEs: "",
      carNameUs: "",
      salary: 0,
      begintime: 0,
      endtime: 0,
      chanceCardEs: ``,
      chanceCardEffectEs: "Cambio de carrera a  | nivel  - ",
      descriptionEs: ``,
      promotionEs: "",
      promotionUs: "",
      moodChangesPerHour: [0, 0, 0, 0, 0, 0, 0],
      friends: 0,
      skills: [0, 0, 0, 0, 0, 0],
    },
  ],
};
